
export const RECEIVE_PAGE = 'RECEIVE_PAGE';
export const RECEIVE_POSTS = 'RECEIVE_POSTS';
export const RECEIVE_POST = 'RECEIVE_POST';

export const POSTS_PER_PAGE = 10;

export const RECEIVE_CATEGORIES = 'RECEIVE_CATEGORIES';